//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassesUser
    {
        public int UserID { get; set; }
        public int ClassID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual User User { get; set; }
    }
}
