//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public bool IsPay { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual User User { get; set; }
    }
}
